"""
StreamGuard — Spark Structured Streaming Fraud Detector
=========================================================
This is the heart of the pipeline. It reads live transactions from Kafka,
applies fraud detection rules in real time, and writes results to:
  1. Kafka topic `fraud-alerts`   — flagged transactions only
  2. Console output               — for monitoring/debugging

Architecture note:
  - Reads from Kafka topic: raw-transactions
  - Writes to Kafka topic:  fraud-alerts
  - Each Kafka message key = customer_id (ensures same partition = accurate velocity)

How to run (local mode, no cluster needed):
  python spark/fraud_detector.py

How to run on Spark cluster (Docker):
  docker exec streamguard-spark-master spark-submit \
    --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 \
    /opt/spark/work-dir/spark/fraud_detector.py

What you need first:
  pip install pyspark==3.5.0

Beginner tip — what is Structured Streaming?
  Normal Spark reads a static file (like a CSV) and processes it once.
  Structured Streaming treats a Kafka topic like an infinite DataFrame
  that keeps getting new rows. Spark processes each "micro-batch" of
  new messages every few seconds, applying the same SQL-style logic.
"""

import os
import json
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType,
    BooleanType, TimestampType
)

# Import our fraud rules (same folder)
from fraud_rules import apply_amount_rule, apply_merchant_rule, apply_geo_country_rule, compute_fraud_score

# ── Configuration ──────────────────────────────────────────────────────────────
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9093")
INPUT_TOPIC = "raw-transactions"
OUTPUT_TOPIC = "fraud-alerts"

# How often Spark processes a new micro-batch (lower = lower latency, more CPU)
TRIGGER_INTERVAL = "5 seconds"

# Watermark: how long to wait for late-arriving events.
# If a transaction arrives 30 seconds late, it still gets counted
# in the correct time window. After 30s, we drop it.
WATERMARK_DELAY = "30 seconds"


# ── Schema definition ──────────────────────────────────────────────────────────
# We must tell Spark what the JSON structure looks like.
# This matches the fields generated by kafka/transaction_producer.py
TRANSACTION_SCHEMA = StructType([
    StructField("transaction_id",   StringType(),  nullable=False),
    StructField("customer_id",      StringType(),  nullable=False),
    StructField("customer_name",    StringType(),  nullable=True),
    StructField("timestamp",        StringType(),  nullable=False),  # ISO string, cast later
    StructField("amount",           DoubleType(),  nullable=False),
    StructField("currency",         StringType(),  nullable=True),
    StructField("merchant_name",    StringType(),  nullable=True),
    StructField("merchant_category",StringType(),  nullable=True),
    StructField("merchant_country", StringType(),  nullable=True),
    StructField("customer_lat",     DoubleType(),  nullable=True),
    StructField("customer_lon",     DoubleType(),  nullable=True),
    StructField("card_last4",       StringType(),  nullable=True),
    StructField("card_type",        StringType(),  nullable=True),
    StructField("is_fraud",         BooleanType(), nullable=True),   # Ground truth label
    StructField("fraud_type",       StringType(),  nullable=True),
])


def create_spark_session() -> SparkSession:
    """
    Create a SparkSession configured for Kafka integration.

    The `spark-sql-kafka` package is what lets Spark talk to Kafka.
    It's downloaded automatically by Spark when you include it in --packages.
    """
    return (
        SparkSession.builder
        .appName("StreamGuard-FraudDetector")
        .master("local[*]")   # Use all available CPU cores locally
        .config(
            "spark.jars.packages",
            "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"
        )
        # Reduce verbose Spark logging so fraud alerts stand out
        .config("spark.sql.streaming.statefulOperator.checkCorrectness.enabled", "false")
        .getOrCreate()
    )


def read_from_kafka(spark: SparkSession):
    """
    Create a streaming DataFrame from the Kafka topic.

    Kafka gives us each message as binary (bytes). The key columns are:
      - value: the JSON payload (our transaction), as bytes
      - key:   the message key (customer_id), as bytes
      - timestamp: when Kafka received the message

    We use `startingOffsets="latest"` so we only process new messages,
    not historical ones sitting in the topic.
    """
    return (
        spark.readStream
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
        .option("subscribe", INPUT_TOPIC)
        .option("startingOffsets", "latest")
        .option("failOnDataLoss", "false")
        .load()
    )


def parse_transactions(kafka_df):
    """
    Convert raw Kafka bytes → structured transaction DataFrame.

    Step by step:
      1. Cast binary `value` to a string
      2. Parse that string as JSON using our schema
      3. Cast the ISO timestamp string to a proper Spark TimestampType
      4. Add a watermark so Spark knows how to handle late data
    """
    # Step 1 & 2: decode JSON
    parsed = (
        kafka_df
        .select(
            # F.from_json parses the JSON string into a struct using our schema
            F.from_json(
                F.col("value").cast("string"),
                TRANSACTION_SCHEMA
            ).alias("txn"),
            F.col("timestamp").alias("kafka_timestamp")  # When Kafka received it
        )
        # Flatten the struct into individual columns
        .select("txn.*", "kafka_timestamp")
    )

    # Step 3: convert timestamp string → TimestampType
    parsed = parsed.withColumn(
        "event_time",
        F.to_timestamp(F.col("timestamp"))
    )

    # Step 4: watermark — tells Spark "events can arrive up to 30s late"
    # Without this, Spark would hold state forever for windowed operations
    parsed = parsed.withWatermark("event_time", WATERMARK_DELAY)

    return parsed


def apply_fraud_detection(df):
    """
    Apply all fraud detection rules and compute risk scores.

    Each rule adds two columns: a boolean flag and a reason string.
    Then compute_fraud_score combines them into a 0-100 score + risk level.

    Column flow:
      amount_flag, amount_reason       ← apply_amount_rule()
      merchant_flag, merchant_reason   ← apply_merchant_rule()
      geo_flag, geo_reason             ← apply_geo_country_rule()
      fraud_score, risk_level,
      fraud_reason                     ← compute_fraud_score()
    """
    df = apply_amount_rule(df)
    df = apply_merchant_rule(df)
    df = apply_geo_country_rule(df)
    df = compute_fraud_score(df)
    return df


def prepare_kafka_output(df):
    """
    Format the enriched DataFrame for writing back to Kafka.

    Kafka expects:
      - key:   bytes (we use customer_id)
      - value: bytes (we serialize the full enriched transaction as JSON)

    We only write flagged transactions (fraud_score > 0) to fraud-alerts.
    All transactions go to the console sink for monitoring.
    """
    # Select the columns we want in the output message
    output_cols = [
        "transaction_id", "customer_id", "timestamp", "amount",
        "merchant_name", "merchant_category", "merchant_country",
        "customer_lat", "customer_lon", "card_type",
        "fraud_score", "risk_level", "fraud_reason",
        "amount_flag", "merchant_flag", "geo_flag",
    ]

    fraud_alerts = (
        df
        .filter(F.col("fraud_score") > 0)   # Only flagged transactions
        .select(
            # Key for Kafka partitioning
            F.col("customer_id").alias("key"),
            # Serialize all output columns as JSON for the Kafka message value
            F.to_json(F.struct(*[F.col(c) for c in output_cols])).alias("value")
        )
    )

    return fraud_alerts


def write_to_console(df):
    """
    Write all transactions to console for live monitoring.
    Shows risk level, amount, merchant, and fraud reason.
    Useful for development and demos.
    """
    return (
        df
        .select(
            "customer_id", "transaction_id", "amount",
            "merchant_category", "merchant_country",
            "risk_level", "fraud_score", "fraud_reason"
        )
        .writeStream
        .outputMode("append")
        .format("console")
        .option("truncate", False)
        .option("numRows", 20)
        .trigger(processingTime=TRIGGER_INTERVAL)
        .start()
    )


def write_to_kafka(df):
    """
    Write fraud alerts back to Kafka topic `fraud-alerts`.

    Downstream consumers (dashboard, Snowflake writer) subscribe to this
    topic using their own consumer groups — they read independently.

    checkpointLocation: Spark saves progress here so if the job crashes,
    it resumes from where it left off rather than reprocessing old data.
    """
    fraud_alerts = prepare_kafka_output(df)

    return (
        fraud_alerts
        .writeStream
        .outputMode("append")
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
        .option("topic", OUTPUT_TOPIC)
        .option("checkpointLocation", "/tmp/streamguard-checkpoint-kafka")
        .trigger(processingTime=TRIGGER_INTERVAL)
        .start()
    )


def main():
    print("=" * 60)
    print("StreamGuard Fraud Detector starting...")
    print(f"  Kafka: {KAFKA_BOOTSTRAP_SERVERS}")
    print(f"  Input: {INPUT_TOPIC}  →  Output: {OUTPUT_TOPIC}")
    print(f"  Trigger interval: {TRIGGER_INTERVAL}")
    print(f"  Watermark delay:  {WATERMARK_DELAY}")
    print("=" * 60)

    # 1. Create Spark session
    spark = create_spark_session()
    spark.sparkContext.setLogLevel("WARN")   # Reduce noise in logs

    # 2. Read streaming data from Kafka
    raw_stream = read_from_kafka(spark)

    # 3. Parse JSON messages into structured columns
    transactions = parse_transactions(raw_stream)

    # 4. Apply all fraud detection rules
    enriched = apply_fraud_detection(transactions)

    # 5. Write to console (all transactions, for monitoring)
    console_query = write_to_console(enriched)

    # 6. Write fraud alerts back to Kafka
    kafka_query = write_to_kafka(enriched)

    print("\nStreaming queries running. Press Ctrl+C to stop.")
    print("Waiting for transactions from Kafka...\n")

    # Keep the job running until interrupted
    try:
        spark.streams.awaitAnyTermination()
    except KeyboardInterrupt:
        print("\nShutting down fraud detector...")
        console_query.stop()
        kafka_query.stop()
        spark.stop()
        print("Done.")


if __name__ == "__main__":
    main()
